micronaut:
  server:
    port: 8080
    cors:
      enabled: true
  application:
    name: raspi-finance-enpoint-micronaut
datasources:
  default:
    url: jdbc:postgresql://hornsup:5432/finance_db
    driverClassName: org.postgresql.Driver
    username: henninb
    password: monday1
    schema-generate: NONE
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true
